// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SX_CraftBox","status":true,"description":"Supports for crafting items.","parameters":{}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}}
];
